PAY_ERROR_CODES = {
    '101': 'Version Empty or not 1.0',
    '102': 'Timestamp empty or not in ISO Format',
    '103': 'orgId is not available in Database',
    '104': 'msgId is not in correct format or empty',
    '105': 'Txn Id is empty or not in correct format',
    '106': 'TagId is not in correct format or empty',
    '108': 'Org Id is empty or not in correct format',
    '112': 'TID is empty or not in correct format',
    '113': 'Vehicle Class is empty or not in correct format',
    '114': 'Vehicle class not available in Database',
    '115': 'RegNo empty or not in correct format',
    '118': 'Exception code is empty or not in correct format',
    '119': 'Exception code not in Database',
    '124': 'OrgId is Inactive',
    '125': 'TagId is not present in Database',
    '126': 'Amount empty or not in correct format',
    '127': 'Plaza code empty or not in correct format',
    '133': 'Counter is empty or not in correct format',
    '138': 'Empty Request',
    '139': 'Head Element is not available',
    '140': 'Transaction Element is not available',
    '141': 'Note is not in correct format',
    '142': 'RefId is not in correct format',
    '143': 'RefUrl is not in correct format',
    '144': 'Txn Type is empty or not in the list of types',
    '145': 'Vehicle Tag is null',
    '147': 'Request is not in correct format',
    '150': 'Lane Reader ID is empty or not in correct format',
    '159': 'Last Fetch Time is greater than 24 hours or future time',
    '160': 'Last fetch time is empty or not in correct format',
    '161': 'Risk Score Provider is empty or is not in correct format',
    '162': 'risk score type is empty or not in correct format',
    '163': 'risk score value is empty is not in correct format',
    '164': 'TID ID not mapped with given tagId',
    '165': 'AVC not in correct format',
    '166': 'Plaza name not in correct format',
    '167': 'Plaza geocode is empty or not in correct format',
    '168': 'Plaza type is empty or not in correct format',
    '169': 'Lane Id is empty or not in correct format',
    '170': 'Lane Directon is empty ot not in correct format',
    '171': 'Reader Read time is empty or not in correct format',
    '172': 'Reader Read Time cannot be more than txn time',
    '173': 'Maximum days to push older transactions exceeds',
    '174': 'orgTxnId is not in correct format',
    '175': 'Amount should be zero as tagId is in exemption Code',
    '176': 'Cannot initiate TXN as Tag is in Black List or Low Balance List',
    '178': 'Plaza not available in Database',
    '179': 'Plaza not associated with Acquirer ID',
    '180': 'Plaza type is not same as available in DB',
    '181': 'Lane attributes should be empty in case of Plaza type as Parking',
    '185': 'Reader Id is empty or not in correct format',
    '186': 'VEHICLE DETAILS are not in correct format',
    '187': 'Vehicle Class is not associated with tagId',
    '188': 'Reg no. is not associated with tagId',
    '191': 'ExcCode is not associated with tagId',
    '196': 'Currency is empty or not in correct format',
    '198': 'Avc Not in DB',
    '201': 'Transaction ID+Merchant ID+Lane ID should be unique for a transaction',
    '202': 'Meta Element is missing',
    '203': 'Amount should be zero if txn type is ZERO_TXN',
    '205': 'Future Timestamp should not be acceptable',
    '206': 'Not allowed to use particular service',
    '207': 'Exception Code is already added by other bank',
    '208': 'No privledges to add exception Code',
    '209': 'tag Verified is empty or not in correct format',
    '210': 'Public Key CVV is mandatory if TID verified is netc tag',
    '212': 'Public Key CVV is not in correct format',
    '213': 'Sign Auth is not valid',
    '214': 'procRestrictionResult is not in correct format',
    '215': 'Vehicle Auth is not valid',
    '216': 'Txn Counter is empty or not in correct format',
    '217': 'Txn Status is empty or not in correct format',
    '218': 'Txn Amount should be zero if txn status is FAILED',
    '221': 'Heart Beat Msg Type is not in predefined types',
    '222': "Heart Beat msg Acquirer Id is not matched with OrgId's acquirer ",
    '225': 'Lane status is empty or not in correct format',
    '231': 'Comvehicle is Empty or not in correct format',
    '232': 'TID is not in DB',
    '233': 'Vehicle Reg No not in DB',
    '234': 'Any one input either tagid or TID or vehicleRegNo should be present for Request Tag Details',
    '235': 'Plaza Subtype is empty or not in correct format',
    '236': 'Plaza Subtype is not same as available in DB',
    '237': 'Commercial Vehicle Flag is not same in DB',
    '239': 'Only one input is allowed either tagid or TID or vehicleRegNo',
    '241': 'One or more attribute is missing in Head Element',
    '242': 'One or more attribute is missing in Txn Element',
    '243': 'One or more attribute is missing in TagList',
    '244': 'One or more attribute is missing in Meta Element',
    '245': 'One or more attribute is missing in Merchant Element',
    '246': 'One or more attribute is missing in Vehicle Element',
    '250': 'One or more attribute is missing in Exception tag',
    '261': 'Signature is not found in request',
    '262': 'Plaza certificate is not found',
    '263': 'Signature is invalid',
    '264': 'TagID not registered with participant',
    '265': 'Invalid IIN',
    '266': 'Merchant Element not available',
    '267': 'Lane Element is not available',
    '269': 'Reader Verification Result Element is not available',
    '272': 'Amount Element is not available',
    '273': 'Riskscores Element is not available',
    '274': 'Score Element is not available',
    '275': 'Vehicle Element is not available',
    '276': 'Vehicle Details Element is not available',
    '277': 'TagList Element is not available',
    '278': 'Tag Element is not available',
    '279': 'ExceptionList Element is not available',
    '280': 'Exception Element is not available',
    '281': 'Amount should not be zero if txn Type is Credit or Debit',
    '284': 'Signature algorithm is not correct',
    '285': 'Digest algorithm is not correct',
    '287': 'Unreadable XML',
    '288': 'OrgTxnId cannot be null in case txn type is CREDIT',
    '290': 'Credit Happened Already for Specified TxnId.',
    '291': 'Credit amount should not be greater than or equal to debit amount',
    '292': 'Credit Reader read time should not be less than Debit Reader read time',
    '293': 'No Txn happened for debit in last three days',
    '294': 'SignData is empty or not in correct format',
    '295': 'No Matching ECC PublicKey found for Issuer IIN and Key Index',
    '296': 'Tag Signature Verification Failed',
    '297': 'PublicKey CVV of Input Message NOT matched with DB value',
    '299': 'Txn Status Should Not Be Failed',
    '301': 'One or more attribute is missing in Status Element',
    '302': 'Status Element is not available',
    '303': 'Incorrect format for Transaction Date',
    '304': 'Transaction Date is of future date',
    '305': "The given combination for a particular transaction doesn't exist", 
    # ... (add more as needed) ...
} 